### ISSUE TITLE
Character teleports upwards instead of jumping

### ISSUE THREAD

**Issue by jdespland-teaching** [jdespland-teaching/CART315class_project_w2019#1]
Locomotion script makes the character teleport upwards instead of jumping. Need to implement smooth jumping physics either by coding them in the script or by switching to a physics component instead of a character controller.

**Comment by Joe-Power** [comment]
I've merged the Locomotion user and control script into the one LocomotionControl. Its not too dissimilar to what we originally had but the teleportation is gone
