### ISSUE TITLE
Navmesh script is broken

### ISSUE THREAD

**Issue by Jonathan-Ganz** [jdespland-teaching/CART315class_project_w2019#11]
Most all textures and scripts are disconnected, and for the life of me I am not fully clear on how it is supposed to be called in terms of Usage. Ideally If I feed the script a location (in vector3 format) it should do the rest of the work.

I raise the issue because the behavior and targeting script will need to be able to call and use the navmesh with nothing more than the target's location

**Comment by allanpichardo** [comment]
Hi @Jonathan-Ganz I'm not on the Navmesh team, but as far as I know, the way it would work is that you open the navigation window (window->ai->navigation) and then select the terrain you want the agent to be able to walk on. Then select bake. That will turn the surface into a walkable area. Then for any game character that you want to make walk, add a NavMeshAgent component to it. Once you've done that, all you need is a location. Here's an example of what it would look like in your script:

`void Start() {
    navMeshAgent = GetComponent<NavMeshAgent>();
}

void Update() {
    navMeshAgent.SetTarget(theLocationYouWant);
}`

After that, the agent will automatically calculate a path and move to it. Hope this helps

**Comment by emilywumontreal** [comment]
thank you @allanpichardo ! it is helpful.
I fixed the broken scene. now you are supposed to see the scene properly.  you may need an extra navmesh components to make it run properly, which I have uploaded into github: https://github.com/Unity-Technologies/NavMeshComponents. 

I added a gaint navmesh map into the scene, now you could choose humanoid or gaint navmap by changing dropdown menu in the nav mesh agent component of your player.  I am going to add an small size player navmap for furture use. right now for testing , two type of navmesh is good to go.

I also did an instruction about how to use navmesh script in the NavMeshController.cs .please check it if you have any trouble. any other questions, please let me know.

**Comment by emilywumontreal** [comment]
here is trouble shooting reference screenshot
1. assign material into scene 
![Screen Shot 2019-03-18 at 4 49 10 PM](https://user-images.githubusercontent.com/31903463/54562912-561e5680-499e-11e9-89c2-e1f763ce5b41.png)
2. assign navmeshcontroller.cs to player, rigidbodycontroller.cs to player
![Screen Shot 2019-03-18 at 4 49 46 PM](https://user-images.githubusercontent.com/31903463/54563104-c2995580-499e-11e9-9776-592f46647992.png)

3. on navmesh object , remove two components, adding two navmesh surface script. choose agent type to gaint on the second surface script component.  
![Screen Shot 2019-03-18 at 4 50 38 PM](https://user-images.githubusercontent.com/31903463/54563127-cd53ea80-499e-11e9-85c7-788329173b20.png)
![Screen Shot 2019-03-18 at 4 51 11 PM](https://user-images.githubusercontent.com/31903463/54563140-d5ac2580-499e-11e9-86b2-0da2d9f7498e.png)

**Comment by Jonathan-Ganz** [comment]
thank you, i'll try it out once i'm back on a machine that can run unity

**Comment by evoucou** [comment]
Trouble shooting reference, **precision at step 2**.

> 2. assign navmeshcontroller.cs to player, rigidbodycontroller.cs to player
![Screen Shot 2019-03-18 at 4 49 46 PM](https://user-images.githubusercontent.com/31903463/54563104-c2995580-499e-11e9-9776-592f46647992.png)


When you assign both scripts to the player, do not forget to **link the scene objects to the NavMeshController script**. (Just a little step that Emily did not mention, might be obvious but I am mentioning it in case)

Cam Variable is the scene's camera, and Agent Variable has to be the player's Nav Mesh Agent component.

See following screenshots.

![NavMeshController1](https://user-images.githubusercontent.com/31899199/54627852-a226d500-4a4a-11e9-87ff-6952afd68058.jpg)

![NavMeshController2](https://user-images.githubusercontent.com/31899199/54627853-a226d500-4a4a-11e9-9797-fce63e9cfb87.jpg)

**Comment by evoucou** [comment]
Trouble shooting reference, **precision at step 3**.

> 3. on navmesh object , remove two components, adding two navmesh surface script. choose agent type to gaint on the second surface script component.  
![Screen Shot 2019-03-18 at 4 50 38 PM](https://user-images.githubusercontent.com/31903463/54563127-cd53ea80-499e-11e9-85c7-788329173b20.png)
![Screen Shot 2019-03-18 at 4 51 11 PM](https://user-images.githubusercontent.com/31903463/54563140-d5ac2580-499e-11e9-86b2-0da2d9f7498e.png)

In my case, I had to bake both surface scripts for it to work. If you do not see the blue surface on the floor, which is the navigation mesh, it is because you have to hit bake for both;

![NavMeshController3](https://user-images.githubusercontent.com/31899199/54634343-68f56180-4a58-11e9-98d0-02346db474fd.jpg)

Hope this helps anyone who's having trouble with the navmesh test scene.

**Comment by evoucou** [comment]
I will now close this issue as it has been resolved. If anyone has any questions you can write to me or Emily on Slack.
