### ISSUE TITLE
ALL ACTIONS: there should be a way to call each action without the condition of a button being used

### ISSUE THREAD

**Issue by Jonathan-Ganz** [jdespland-teaching/CART315class_project_w2019#19]
Currently actions such as pickupper require a button to be pressed to enact the action.

Make sure that if the checks are necessary that they simply call a function that could otherwise be called by another script (ie. behavior) under the assumption there is no player controlling

**Comment by MartinJohnH** [comment]
This issues has already been added. Currently issue #13. Teams have started to implement function to solve this problem.
