### ISSUE TITLE
Use script can not get doAfterUse() function invoke

### ISSUE THREAD

**Issue by emilywumontreal** [jdespland-teaching/CART315class_project_w2019#21]
I was testing out my Key/Open script. I was taking become script to access usable script and pickup script,

the condition in usable script :  "if (Physics.Raycast(transform.parent.parent.position, transform.forward, out hit, maxDistance)) { " is always false.
I was trying to make it work. So I tried to change the second parameter to "transform.parent.parent.position" for testing . in my case ,it works.   maybe you could double check this usable script through become script ,  see if it works.

**Comment by MartinJohnH** [comment]
I think usable as know been implemented with the become script. Are you still having problems?

**Comment by allanpichardo** [comment]
@emilywumontreal I changed the Usable script so that it always uses the forward direction of the player and not the forward direction of the item. This should now work no matter what direction the picked up item points as long as the player points towards the door

**Comment by emilywumontreal** [comment]
Usable scripts has changed the way detecting distance ( by player not pickable object) so now pickable rotation is not a problem anymore .

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
