### ISSUE TITLE
pickable object will change rotation while player is moving ,which causes distance detecter disfunction 

### ISSUE THREAD

**Issue by emilywumontreal** [jdespland-teaching/CART315class_project_w2019#22]
in my key/open script case, the picked up objects will rotate on the top of player while player is moving.  and I guess maybe you want to freeze-rotation of pickupable objects. In my case , the key is supposed to be in front of the door, like useable script requires(which keyopen script rely s on). but it is actually pointing out of other direction. it causes the problem of detecting distance.

**Comment by MartinJohnH** [comment]
So "pickupable" objects have a rigidbody on them so you just need to make sure that you freeze their positions by checking the freeze options on the rigidbody in the inspector. Is this what you mean?

**Comment by allanpichardo** [comment]
The Usable script uses the forward direction of the player, not the picked up object. So it shouldn't matter if the key is facing another direction. As long as the player's forward vector is pointing towards the UseTarget, it should work
