### ISSUE TITLE
There should be an easy way to know if objects are held or are holding another

### ISSUE THREAD

**Issue by jdespland-teaching** [jdespland-teaching/CART315class_project_w2019#4]
For tasks like eating, throwing, using, etc, objects need to know what object is held or if they're being held. This functionality should be provided by the pickup script.

**Comment by allanpichardo** [comment]
Since I'm working on use and throw and need quick access to this, I'm adding a simple public method to this script

**Comment by allanpichardo** [comment]
The Pickupper script now has a public boolean method IsHoldingObject()
