### ISSUE TITLE
Locomotion script doesn't rotate the character

### ISSUE THREAD

**Issue by allanpichardo** [jdespland-teaching/CART315class_project_w2019#5]
The movement in the locomotion script only strafes, but the throwing mechanic requires a character to be able to turn towards another so that they can throw something

**Comment by chortletortle** [comment]
Would a method turning the object towards a vector be ok? LMK if you have a preferred way and we'll figure it out shortly :-)

**Comment by allanpichardo** [comment]
Yeah something like a method that makes the character turn to face a given
target

**Comment by MartinJohnH** [comment]
Also, if a player is rotated in another direction other than (0,0,0) the player does not move forward, the player keeps moving along its initial axis.

**Comment by MartinJohnH** [comment]
Fixed
