### ISSUE TITLE
Become Script - Prefab Bug

### ISSUE THREAD

**Issue by matteomannarino** [jdespland-teaching/CART315class_project_w2019#6]
Currently, the Become script is working well on personal computers but there is an issue when attempting to pull the current version and load the script.

1) Delete Become(script) attached to Camera_Become

2) Camera_Become prefab is not recognized immediately, can be temporarily fixed by deleted prefab on Player 1 and re-attaching the prefab

Console error: Could not locate ProBuilder/Icons folder.  The ProBuilder folder may be moved, but the contents of this folder must remain unmodified relative to ProBuilder root.
UnityEngine.Debug:LogError(Object)
ProBuilder2.EditorCommon.pb_IconUtility:.cctor()
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()

Is anyone else experiencing this console error above?

**Comment by MartinJohnH** [comment]
Problem should be fixed now that the prefabs get correctly added
