### ISSUE TITLE
key/open task requires "Use" script . we could not find it by now

### ISSUE THREAD

**Issue by emilywumontreal** [jdespland-teaching/CART315class_project_w2019#8]
can use team provide a solid version to us? thanks

**Comment by allanpichardo** [comment]
Hi @emilywumontreal there are two scripts in the project. One called `Usable` and another called `UseTarget`. Put the `Usable` script on the thing being used (the key) and put the `UseTarget` script on the door.

You would use it by getting the Usable component like so: `var usable = GetComponent<Usable>()` and then you can use it by calling the use function `usable.Use()` if you're in front of a UseTarget or `usable.Use(object)` if you need to specify an explicit object somewhere else.

In the editor, when you click on your UseTarget object, you'll notice there's a gray area that says `On Target Used` and a + sign. Here you can add callbacks to whatever function you want to be called when the object gets used. Wherever you implement this function, just drag and drop the object into it and select the name of the function you want to call.

If you have any more questions, let me know, or you can take a look at the UseTest scene to see an example
